### ISSUE TITLE
Canvas renderer does not work on chrome OS.

### ISSUE THREAD

**Issue by moleCuleFFF** [giniedp/spritespin#41] opened 2018-04-04 11:20 UTC
jurassicworldevolution.com/research -> example

**Comment by giniedp** [comment] 2018-04-04 12:47
i dont have a chrome OS device to test with but will install a virtual box image later today.

**Comment by moleCuleFFF** [comment] 2018-04-04 13:04
Let me know if you need any more info about the source code as the JS is minified and compressed.

**Comment by giniedp** [comment] 2018-04-04 13:27
Can you give me some more details about the device and the chrome OS version?

I have downloaded the chromium browser, and it seems to work. It might take me a while to get a proper virtual box image.

**Comment by moleCuleFFF** [comment] 2018-04-04 14:27
So it works absolutely fine on all versions of chrome except across the board on android as far as I can tell. It also works if you set the renderer to image but for various reasons I require the canvas renderer.
It seems to reproduce the same issue if you don't tell spritesmith about the framesX.

**Comment by moleCuleFFF** [comment] 2018-04-04 14:39
It appears that the canvasRatio is not being set correctly.
On chrome android it is set at 4. Everywhere else it is 2.625

**Comment by giniedp** [comment] 2018-04-04 19:15
which version of spritespin do you use? There has been an issue with hi def canvas which i had fixed recently
https://github.com/giniedp/spritespin/commit/82d062863f78e0de3c2abcc31608f3a5ccd2b95f

**Comment by giniedp** [comment] 2018-04-04 19:25
looking through the sourcecode on the page it seems you have an older version of spritespin. Please try a recent version which you can get here

http://unpkg.com/spritespin@x.x.x/release/spritespin.js

or via NPM

`npm install spritespin`

The examples from the website do work under android

http://spritespin.ginie.eu/samples/#/basics-basics

**Comment by moleCuleFFF** [comment] 2018-04-05 10:31
I'll try updating thanks m8, am using yarn so the lock file may well be out of date.

**Comment by giniedp** [comment] 2018-04-05 13:28
i see you use pretty large spritesheets. Maybe it is related to #42 
May i use one of your images to investigate the issue isolated from the website you are working on?

**Comment by giniedp** [comment] 2018-04-05 14:54
the solution i mentioned is not functional yet (multiple sprite sheets), but i am working on it

**Comment by giniedp** [comment] 2018-04-05 15:38
closed in favor of #43

**Closed** 2018-04-05 15:38 UTC
